### ISSUE TITLE
newest scripts

### ISSUE THREAD

**Issue by endoleg** [controlup/script-library#3]
At https://github.com/controlup/script-library/ there are the newest copies of the latest available ControlUp Scripts sourced from https://www.controlup.com/script-library/

Now there are 2 Scripts missing:

Generate Windows Event
Version: 1.0.10  |   Created: 2021-03-31  |   Modified: 2021-03-31  |   Creator: wouter.kursten  |   Downloads: 3
Delete local users profile
Version: 1.7.8  |   Created: 2021-03-25  |   Modified: 2021-03-25  |   Creator: jennifer.anosa  |   Downloads: 8

Could you upload them here, please?

**Comment by MarkusZehnle** [comment]
I second this.
Maybe you (@ControlUp) can add the XML for importing the Script Actions into Console here aswell!?

**Comment by Magneet** [comment]
I have requested the sync to be done. The generate windows event should show up soon, the other one was removed as it wasn't useful. I am not sure if we can create the xml files though but if you would like to have one just email support@controlup.com

**Comment by controlupscriptlibrary** [comment]
All scripts have been updated, and as of last week the script folders contain the XML files as well.
